server:
  host: 0.0.0.0
  port: 8330
  timeout:
    read: 5s
    write: 10s
    idle: 15s
    shutdown: 30s
  rate:
    enabled: true
    rps: 2
log:
  level: info
redis:
  host: 172.17.0.2
  port: 6379
