server:
  host: localhost
  port: 8330
  timeout:
    read: 5s
    write: 10s
    idle: 15s
    shutdown: 30s
  rate:
    enabled: false
    rps: 2
log:
  level: info
redis:
  host: 127.0.0.1
  port: 6379
